"""Initial migration.

Revision ID: 551960bd161b
Revises: 
Create Date: 2022-03-13 22:50:58.586812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551960bd161b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'complete')
    # ### end Alembic commands ###
